### ISSUE TITLE
tg downloader blazor

### ISSUE THREAD

**Issue by frezeen** [DamianMorozov/TgDownloader#56]
my test with it:

dockerized on  OMV 7

this is stack:

```
services:
  tgdownloader-blazor:
    image: damianmorozov/tgdownloader-blazor:latest
    ports:
     - "7682:7682"
    environment:
     - TZ=Europe/Rome
    # volumes:
    # - ./TgDownloader.db:/app/TgDownloader.db:rw # optional
    # - ./TgDownloader.xml:/app/TgDownloader.xml:rw # optional
    # - ./TgDownloader.session:/app/TgDownloader.session:rw # optional
    container_name: tgdownloader-blazor
    restart: on-failure
```

```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {c50f05d4-ee3a-45a6-a765-e9f40d8acda2} may be persisted to storage in unencrypted form.
warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
      Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://0.0.0.0:7682'.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:7682
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.UnauthorizedAccessException: Access to the path '/app/TgDownloader.xml' is denied.
       ---> System.IO.IOException: Permission denied
         --- End of inner exception stack trace ---


```

**Comment by AndreaZoppi** [comment]
Same problem here:

```
2024-04-22T12:34:07.676716853Z          at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
2024-04-22T12:34:07.676720667Z          at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2024-04-22T12:34:07.676724230Z          at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
2024-04-22T12:34:07.676728189Z          at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
2024-04-22T12:34:07.676731882Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
2024-04-22T12:34:07.676735702Z          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
2024-04-22T12:34:07.676739485Z          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
2024-04-22T12:34:07.676743424Z          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
2024-04-22T12:34:07.676747189Z          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
2024-04-22T12:34:07.676751259Z          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
2024-04-22T12:34:07.676755509Z          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-04-22T12:34:07.676759632Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-04-22T12:34:07.676763661Z       --- End of stack trace from previous location ---
2024-04-22T12:34:07.676766971Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-04-22T12:34:07.676770681Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
2024-04-22T12:34:07.676773278Z          at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.SetParametersAsync(ParameterView parameters)
2024-04-22T12:34:07.676781770Z          at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
2024-04-22T12:34:07.676786576Z       --- End of stack trace from previous location ---
2024-04-22T12:34:07.676790816Z          at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
2024-04-22T12:34:07.676794407Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
2024-04-22T12:34:07.676798081Z          at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
2024-04-22T12:34:07.676802052Z          at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.<>c__DisplayClass35_0.<PrerenderComponentAsync>b__0()
2024-04-22T12:34:07.676806400Z          at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<InvokeAsync>g__Execute|9_0[TResult](ValueTuple`3 state)
2024-04-22T12:34:07.676810732Z       --- End of stack trace from previous location ---
2024-04-22T12:34:07.676814539Z          at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.PrerenderComponentAsync(HttpContext httpContext, Type componentType, IComponentRenderMode prerenderMode, ParameterView parameters, Boolean waitForQuiescence)
2024-04-22T12:34:07.676818528Z          at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
2024-04-22T12:34:07.676822091Z          at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
2024-04-22T12:34:07.676825945Z          at TgDownloaderBlazor.Pages.Pages__Host.<ExecuteAsync>b__14_1()
2024-04-22T12:34:07.676829808Z          at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
2024-04-22T12:34:07.676833868Z          at TgDownloaderBlazor.Pages.Pages__Host.ExecuteAsync()
2024-04-22T12:34:07.676838656Z          at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
2024-04-22T12:34:07.676842730Z          at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
2024-04-22T12:34:07.676846619Z          at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
2024-04-22T12:34:07.676850334Z          at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2024-04-22T12:34:07.676854050Z          at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2024-04-22T12:34:07.676857820Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-22T12:34:07.676862533Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
2024-04-22T12:34:07.676880127Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-04-22T12:34:07.676885316Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
2024-04-22T12:34:07.676889186Z       --- End of stack trace from previous location ---
2024-04-22T12:34:07.676891661Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-22T12:34:07.676894350Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-04-22T12:34:07.676896813Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-04-22T12:34:07.676899420Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-04-22T12:34:07.676901910Z       --- End of stack trace from previous location ---
2024-04-22T12:34:07.676904266Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-04-22T12:34:07.676912812Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-04-22T12:34:07.676916835Z          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by DamianMorozov** [comment]
Try to use [TgDownloader Blazor Docker](https://hub.docker.com/repository/docker/damianmorozov/tgdownloader-blazor/).

**Comment by frezeen** [comment]
this isnt fixed yet
